server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecomnew?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Casifbasha@98480
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true