spring:
  application:
    name: ApiGateWay

  config:
    import: optional:configserver:http://localhost:8888

#  cloud:
#    gateway:
#      routes:
#        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/users/**
#
#        - id: ORDER-SERVICE
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/api/orders/**, /api/cart/**
#
#        - id: PRODUCT-SERVICE
#          uri: lb://PRODUCT-SERVICE
#          predicates:
#            - Path=/api/product/**

server:
  port: 8085


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  ecomBreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED