server:
  port: 8081

spring:
  application:
    name: order-service

  rabbitmq:
    host: localhost   # use 'rabbitmq' if running inside docker network
    port: 5672
    username: admin
    password: admin123

  datasource:
    url: jdbc:mysql://localhost:3306/ecomnew?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Casifbasha@98480
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  Kafka
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

    topic:
      order-events: order-Topic

# ✅ Custom RabbitMQ properties (used in your @Value)
rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log

  level:
    root: INFO
    com.ecommerce.order: DEBUG
    org.springframework.amqp: DEBUG   # 🔥 helps debug RabbitMQ connection

  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
