spring:
  application:
    name: configServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: classpath:/config


server:
  port: 8888

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    root: INFO
    com.ecommerce.configServer: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB